### ISSUE TITLE
MakeCallback assert-fails in node 0.12

### ISSUE THREAD

**Issue by metamatt** [TooTallNate/node-weak#32]
I'm running some preliminary experiments using the `weak` extension under Node 0.12 (there's no such release yet, but there is [a code branch you can build and run](https://github.com/joyent/node/tree/v0.12), which results in a Node binary claiming to be v0.11.14-pre).

This mostly seems to work fine but I've seen a few sporadic Node process crashes which gdb tells me are at

```
Core was generated by `/home/magi/node-binaries/nodejs-0.12 --harmony --expose_gc --trace_gc /home/mag'.
Program terminated with signal 6, Aborted.
#0  0x00002ae50b34e4f5 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00002ae50b34e4f5 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00002ae50b351c5b in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00002ae50b3471be in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00002ae50b347262 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000000000ae09e4 in node::MakeCallback(node::Environment*, v8::Handle<v8::Value>, v8::Handle<v8::Function>, int, v8::Handle<v8::Value>*) ()
#5  0x0000000000ae1111 in node::MakeCallback(v8::Isolate*, v8::Handle<v8::Object>, v8::Handle<v8::Function>, int, v8::Handle<v8::Value>*) ()
#6  0x00002ae51420fdd8 in void (anonymous namespace)::TargetCallback<v8::Object, (anonymous namespace)::proxy_container>(_NanWeakCallbackData<v8::Object, (anonymous namespace)::proxy_container> const&)
    () from /home/magi/src/node12test/node_modules/weak/build/Release/weakref.node
#7  0x00002ae51420fc98 in void _NanWeakCallbackDispatcher<v8::Object, (anonymous namespace)::proxy_container>(v8::WeakCallbackData<v8::Object, _NanWeakCallbackInfo<v8::Object, (anonymous namespace)::proxy_container> > const&) () from /home/magi/src/node12test/node_modules/weak/build/Release/weakref.node
#8  0x000000000080487f in v8::internal::GlobalHandles::PostGarbageCollectionProcessing(v8::internal::GarbageCollector, v8::internal::GCTracer*) ()
#9  0x000000000082b8d6 in v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GCTracer*, v8::GCCallbackFlags) ()
#10 0x000000000082c0c7 in v8::internal::Heap::CollectGarbage(v8::internal::GarbageCollector, char const*, char const*, v8::GCCallbackFlags) ()
```

The assert in the Node codebase has a comment:

```
  // If you hit this assertion, you forgot to enter the v8::Context first.
  assert(env->context() == env->isolate()->GetCurrentContext());
```

I'm guessing that's exactly the problem, but I don't know if it's weak's job or nan's job to do that.

**Comment by TooTallNate** [comment]
Is this still an issue with v0.4.0?

**Comment by metamatt** [comment]
I was never able to reproduce this outside the original scenario (with a specific codebase on top of weak 0.3.3 and node "0.12" (not the real 0.12.0!). I'm fine with you closing it, and I'll reopen or refile with additional information if I do see it again.

Also, given #36, weak 0.4.0 doesn't call MakeCallback any more, so actually, it can't hit this as things stand right now.

**Comment by TooTallNate** [comment]
w00t! Closing then.
