### ISSUE TITLE
Install fails 

### ISSUE THREAD

**Issue by IonicaBizau** [TooTallNate/node-weak#38]
Any idea why?

```js
$ npm install weak
\
> weak@0.3.3 install /home/ionicabizau/Documents/invoices/node_modules/weak
> node-gyp rebuild

make: Entering directory '/home/ionicabizau/Documents/invoices/node_modules/weak/build'
  CXX(target) Release/obj.target/weakref/src/weakref.o
make: g++: Command not found
weakref.target.mk:84: recipe for target 'Release/obj.target/weakref/src/weakref.o' failed
make: *** [Release/obj.target/weakref/src/weakref.o] Error 127
make: Leaving directory '/home/ionicabizau/Documents/invoices/node_modules/weak/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.16.0-26-lowlatency
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ionicabizau/Documents/invoices/node_modules/weak
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.16.0-26-lowlatency
npm ERR! argv "node" "/usr/local/bin/npm" "install" "weak"
npm ERR! node v0.10.32
npm ERR! npm  v2.1.2
npm ERR! code ELIFECYCLE

npm ERR! weak@0.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the weak@0.3.3 install script.
npm ERR! This is most likely a problem with the weak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls weak
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ionicabizau/Documents/invoices/npm-debug.log
```

## Content of `npm-debug.log`

```sh
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', 'weak' ]
2 info using npm@2.1.2
3 info using node@v0.10.32
4 silly cache add args [ 'weak', null ]
5 verbose cache add spec weak
6 silly cache add parsed spec { raw: 'weak',
6 silly cache add   scope: null,
6 silly cache add   name: 'weak',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 silly addNonLocal parsed spec { raw: 'weak',
7 silly addNonLocal   scope: null,
7 silly addNonLocal   name: 'weak',
7 silly addNonLocal   rawSpec: '',
7 silly addNonLocal   spec: '*',
7 silly addNonLocal   type: 'range' }
8 verbose addNamed weak@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'weak', range: '*', hasData: false }
12 verbose mapToRegistry name weak
13 verbose mapToRegistry uri https://registry.npmjs.org/weak
14 verbose request on initialization, where is /weak
15 verbose request after pass 1, where is /weak
16 verbose request url raw /weak
17 verbose request resolving registry [ 'https://registry.npmjs.org/', './weak' ]
18 verbose request after pass 2, where is https://registry.npmjs.org/weak
19 verbose request no auth needed
20 info attempt registry request try #1 at 12:04:26
21 verbose request id 078953c89d37dbaf
22 verbose etag "4FYI1V3DERRMM5HMRF660H4XG"
23 http request GET https://registry.npmjs.org/weak
24 http 304 https://registry.npmjs.org/weak
25 silly registry.get cb [ 304,
25 silly registry.get   { date: 'Fri, 12 Dec 2014 10:04:27 GMT',
25 silly registry.get     server: 'Apache',
25 silly registry.get     via: '1.1 varnish',
25 silly registry.get     'last-modified': 'Fri, 12 Dec 2014 10:04:27 GMT',
25 silly registry.get     'cache-control': 'max-age=60',
25 silly registry.get     etag: '"4FYI1V3DERRMM5HMRF660H4XG"',
25 silly registry.get     age: '0',
25 silly registry.get     'x-served-by': 'cache-ams4131-AMS',
25 silly registry.get     'x-cache': 'HIT',
25 silly registry.get     'x-cache-hits': '1',
25 silly registry.get     'x-timer': 'S1418378667.586443,VS0,VE377',
25 silly registry.get     vary: 'Accept',
25 silly registry.get     'content-length': '0',
25 silly registry.get     'keep-alive': 'timeout=10, max=50',
25 silly registry.get     connection: 'Keep-Alive' } ]
26 verbose etag https://registry.npmjs.org/weak from cache
27 silly addNameRange number 2 { name: 'weak', range: '*', hasData: true }
28 silly addNameRange versions [ 'weak',
28 silly addNameRange   [ '0.0.1',
28 silly addNameRange     '0.1.0',
28 silly addNameRange     '0.1.1',
28 silly addNameRange     '0.1.2',
28 silly addNameRange     '0.1.3',
28 silly addNameRange     '0.1.4',
28 silly addNameRange     '0.1.5',
28 silly addNameRange     '0.2.0',
28 silly addNameRange     '0.2.1',
28 silly addNameRange     '0.2.2',
28 silly addNameRange     '0.3.0',
28 silly addNameRange     '0.3.1',
28 silly addNameRange     '0.3.2',
28 silly addNameRange     '0.3.3' ] ]
29 verbose addNamed weak@0.3.3
30 silly addNamed semver.valid 0.3.3
31 silly addNamed semver.validRange 0.3.3
32 silly install resolved [ { author: { name: 'Ben Noordhuis', email: 'info@bnoordhuis.nl' },
32 silly install resolved     contributors: [ [Object] ],
32 silly install resolved     name: 'weak',
32 silly install resolved     description: 'Make weak references to JavaScript Objects.',
32 silly install resolved     keywords:
32 silly install resolved      [ 'weak',
32 silly install resolved        'reference',
32 silly install resolved        'js',
32 silly install resolved        'javascript',
32 silly install resolved        'object',
32 silly install resolved        'function',
32 silly install resolved        'callback' ],
32 silly install resolved     version: '0.3.3',
32 silly install resolved     repository:
32 silly install resolved      { type: 'git',
32 silly install resolved        url: 'git://github.com/TooTallNate/node-weak.git' },
32 silly install resolved     main: 'lib/weak.js',
32 silly install resolved     scripts:
32 silly install resolved      { test: 'mocha -gc --reporter spec',
32 silly install resolved        install: 'node-gyp rebuild' },
32 silly install resolved     dependencies: { bindings: '*', nan: '~1.2.0' },
32 silly install resolved     devDependencies: { mocha: '~1.20.1' },
32 silly install resolved     gypfile: true,
32 silly install resolved     bugs: { url: 'https://github.com/TooTallNate/node-weak/issues' },
32 silly install resolved     homepage: 'https://github.com/TooTallNate/node-weak',
32 silly install resolved     _id: 'weak@0.3.3',
32 silly install resolved     _shasum: '12ede888e3732f8634b4586102dcb620b5eb5311',
32 silly install resolved     _from: 'weak@*',
32 silly install resolved     _npmVersion: '1.4.9',
32 silly install resolved     _npmUser: { name: 'tootallnate', email: 'nathan@tootallnate.net' },
32 silly install resolved     maintainers: [ [Object], [Object] ],
32 silly install resolved     dist:
32 silly install resolved      { shasum: '12ede888e3732f8634b4586102dcb620b5eb5311',
32 silly install resolved        tarball: 'http://registry.npmjs.org/weak/-/weak-0.3.3.tgz' },
32 silly install resolved     directories: {},
32 silly install resolved     _resolved: 'https://registry.npmjs.org/weak/-/weak-0.3.3.tgz',
32 silly install resolved     readme: 'ERROR: No README data found!' } ]
33 info install weak@0.3.3 into /home/ionicabizau/Documents/invoices
34 info installOne weak@0.3.3
35 verbose locking weak with /home/ionicabizau/.npm/_locks/weak-340264ce2fa49f33.lock
36 verbose unbuild node_modules/weak
37 verbose gentlyRm vacuuming /home/ionicabizau/Documents/invoices/node_modules/weak
38 verbose tar unpack /home/ionicabizau/.npm/weak/0.3.3/package.tgz
39 verbose tar unpacking to /home/ionicabizau/Documents/invoices/node_modules/weak
40 verbose gentlyRm vacuuming /home/ionicabizau/Documents/invoices/node_modules/weak
41 silly gunzTarPerm modes [ '775', '664' ]
42 silly gunzTarPerm extractEntry package.json
43 silly gunzTarPerm modified mode [ 'package.json', 420, 436 ]
44 silly gunzTarPerm extractEntry .npmignore
45 silly gunzTarPerm modified mode [ '.npmignore', 420, 436 ]
46 silly gunzTarPerm extractEntry README.md
47 silly gunzTarPerm modified mode [ 'README.md', 420, 436 ]
48 silly gunzTarPerm extractEntry LICENSE
49 silly gunzTarPerm modified mode [ 'LICENSE', 420, 436 ]
50 silly gunzTarPerm extractEntry History.md
51 silly gunzTarPerm modified mode [ 'History.md', 420, 436 ]
52 silly gunzTarPerm extractEntry appveyor.yml
53 silly gunzTarPerm modified mode [ 'appveyor.yml', 420, 436 ]
54 silly gunzTarPerm extractEntry .travis.yml
55 silly gunzTarPerm modified mode [ '.travis.yml', 420, 436 ]
56 silly gunzTarPerm extractEntry lib/weak.js
57 silly gunzTarPerm modified mode [ 'lib/weak.js', 420, 436 ]
58 silly gunzTarPerm extractEntry src/weakref.cc
59 silly gunzTarPerm modified mode [ 'src/weakref.cc', 420, 436 ]
60 silly gunzTarPerm extractEntry test/buffer.js
61 silly gunzTarPerm modified mode [ 'test/buffer.js', 420, 436 ]
62 silly gunzTarPerm extractEntry test/callback.js
63 silly gunzTarPerm modified mode [ 'test/callback.js', 420, 436 ]
64 silly gunzTarPerm extractEntry test/create.js
65 silly gunzTarPerm modified mode [ 'test/create.js', 420, 436 ]
66 silly gunzTarPerm extractEntry test/exports.js
67 silly gunzTarPerm modified mode [ 'test/exports.js', 420, 436 ]
68 silly gunzTarPerm extractEntry test/weakref.js
69 silly gunzTarPerm modified mode [ 'test/weakref.js', 420, 436 ]
70 silly gunzTarPerm extractEntry binding.gyp
71 silly gunzTarPerm modified mode [ 'binding.gyp', 420, 436 ]
72 info preinstall weak@0.3.3
73 silly cache add args [ 'bindings@*', null ]
74 verbose cache add spec bindings@*
75 silly cache add parsed spec { raw: 'bindings@*',
75 silly cache add   scope: null,
75 silly cache add   name: 'bindings',
75 silly cache add   rawSpec: '*',
75 silly cache add   spec: '*',
75 silly cache add   type: 'range' }
76 silly cache add args [ 'nan@~1.2.0', null ]
77 verbose cache add spec nan@~1.2.0
78 silly cache add parsed spec { raw: 'nan@~1.2.0',
78 silly cache add   scope: null,
78 silly cache add   name: 'nan',
78 silly cache add   rawSpec: '~1.2.0',
78 silly cache add   spec: '>=1.2.0 <1.3.0',
78 silly cache add   type: 'range' }
79 silly addNonLocal parsed spec { raw: 'bindings@*',
79 silly addNonLocal   scope: null,
79 silly addNonLocal   name: 'bindings',
79 silly addNonLocal   rawSpec: '*',
79 silly addNonLocal   spec: '*',
79 silly addNonLocal   type: 'range' }
80 verbose addNamed bindings@*
81 silly addNamed semver.valid null
82 silly addNamed semver.validRange *
83 silly addNameRange { name: 'bindings', range: '*', hasData: false }
84 verbose mapToRegistry name bindings
85 verbose mapToRegistry uri https://registry.npmjs.org/bindings
86 silly addNonLocal parsed spec { raw: 'nan@~1.2.0',
86 silly addNonLocal   scope: null,
86 silly addNonLocal   name: 'nan',
86 silly addNonLocal   rawSpec: '~1.2.0',
86 silly addNonLocal   spec: '>=1.2.0 <1.3.0',
86 silly addNonLocal   type: 'range' }
87 verbose addNamed nan@>=1.2.0 <1.3.0
88 silly addNamed semver.valid null
89 silly addNamed semver.validRange >=1.2.0 <1.3.0
90 silly addNameRange { name: 'nan', range: '>=1.2.0 <1.3.0', hasData: false }
91 verbose mapToRegistry name nan
92 verbose mapToRegistry uri https://registry.npmjs.org/nan
93 verbose request on initialization, where is /bindings
94 verbose request after pass 1, where is /bindings
95 verbose request url raw /bindings
96 verbose request resolving registry [ 'https://registry.npmjs.org/', './bindings' ]
97 verbose request after pass 2, where is https://registry.npmjs.org/bindings
98 verbose request no auth needed
99 info attempt registry request try #1 at 12:04:27
100 verbose etag "6SJRISMK25A1UDWM33HHCDB3Q"
101 http request GET https://registry.npmjs.org/bindings
102 verbose request on initialization, where is /nan
103 verbose request after pass 1, where is /nan
104 verbose request url raw /nan
105 verbose request resolving registry [ 'https://registry.npmjs.org/', './nan' ]
106 verbose request after pass 2, where is https://registry.npmjs.org/nan
107 verbose request no auth needed
108 info attempt registry request try #1 at 12:04:27
109 verbose etag "BASL4AHUZL2X9BYWJN23MGK84"
110 http request GET https://registry.npmjs.org/nan
111 http 304 https://registry.npmjs.org/bindings
112 silly registry.get cb [ 304,
112 silly registry.get   { date: 'Fri, 12 Dec 2014 10:04:28 GMT',
112 silly registry.get     server: 'Apache',
112 silly registry.get     via: '1.1 varnish',
112 silly registry.get     'last-modified': 'Fri, 12 Dec 2014 10:04:28 GMT',
112 silly registry.get     'cache-control': 'max-age=60',
112 silly registry.get     etag: '"6SJRISMK25A1UDWM33HHCDB3Q"',
112 silly registry.get     age: '0',
112 silly registry.get     'x-served-by': 'cache-ams4121-AMS',
112 silly registry.get     'x-cache': 'HIT',
112 silly registry.get     'x-cache-hits': '1',
112 silly registry.get     'x-timer': 'S1418378668.283457,VS0,VE89',
112 silly registry.get     vary: 'Accept',
112 silly registry.get     'content-length': '0',
112 silly registry.get     'keep-alive': 'timeout=10, max=50',
112 silly registry.get     connection: 'Keep-Alive' } ]
113 verbose etag https://registry.npmjs.org/bindings from cache
114 silly addNameRange number 2 { name: 'bindings', range: '*', hasData: true }
115 silly addNameRange versions [ 'bindings',
115 silly addNameRange   [ '0.0.1',
115 silly addNameRange     '0.1.0',
115 silly addNameRange     '0.1.1',
115 silly addNameRange     '0.2.0',
115 silly addNameRange     '0.2.1',
115 silly addNameRange     '0.2.2',
115 silly addNameRange     '0.2.3',
115 silly addNameRange     '0.2.4',
115 silly addNameRange     '0.3.0',
115 silly addNameRange     '0.4.0',
115 silly addNameRange     '1.0.0',
115 silly addNameRange     '1.1.0',
115 silly addNameRange     '1.1.1',
115 silly addNameRange     '1.2.0',
115 silly addNameRange     '1.2.1' ] ]
116 verbose addNamed bindings@1.2.1
117 silly addNamed semver.valid 1.2.1
118 silly addNamed semver.validRange 1.2.1
119 http 304 https://registry.npmjs.org/nan
120 silly registry.get cb [ 304,
120 silly registry.get   { date: 'Fri, 12 Dec 2014 10:04:28 GMT',
120 silly registry.get     server: 'Apache',
120 silly registry.get     via: '1.1 varnish',
120 silly registry.get     'last-modified': 'Fri, 12 Dec 2014 10:04:28 GMT',
120 silly registry.get     'cache-control': 'max-age=60',
120 silly registry.get     etag: '"BASL4AHUZL2X9BYWJN23MGK84"',
120 silly registry.get     age: '0',
120 silly registry.get     'x-served-by': 'cache-ams4123-AMS',
120 silly registry.get     'x-cache': 'HIT',
120 silly registry.get     'x-cache-hits': '1',
120 silly registry.get     'x-timer': 'S1418378668.271183,VS0,VE165',
120 silly registry.get     vary: 'Accept',
120 silly registry.get     'content-length': '0',
120 silly registry.get     'keep-alive': 'timeout=10, max=50',
120 silly registry.get     connection: 'Keep-Alive' } ]
121 verbose etag https://registry.npmjs.org/nan from cache
122 silly addNameRange number 2 { name: 'nan', range: '>=1.2.0 <1.3.0', hasData: true }
123 silly addNameRange versions [ 'nan',
123 silly addNameRange   [ '0.3.0-wip',
123 silly addNameRange     '0.3.0-wip2',
123 silly addNameRange     '0.3.0',
123 silly addNameRange     '0.3.1',
123 silly addNameRange     '0.3.2',
123 silly addNameRange     '0.4.0',
123 silly addNameRange     '0.4.1',
123 silly addNameRange     '0.4.2',
123 silly addNameRange     '0.4.3',
123 silly addNameRange     '0.4.4',
123 silly addNameRange     '0.5.0',
123 silly addNameRange     '0.5.1',
123 silly addNameRange     '0.5.2',
123 silly addNameRange     '0.6.0',
123 silly addNameRange     '0.7.0',
123 silly addNameRange     '0.7.1',
123 silly addNameRange     '0.8.0',
123 silly addNameRange     '1.0.0',
123 silly addNameRange     '1.1.0',
123 silly addNameRange     '1.1.1',
123 silly addNameRange     '1.1.2',
123 silly addNameRange     '1.2.0',
123 silly addNameRange     '1.3.0',
123 silly addNameRange     '1.4.0',
123 silly addNameRange     '1.4.1' ] ]
124 verbose addNamed nan@1.2.0
125 silly addNamed semver.valid 1.2.0
126 silly addNamed semver.validRange 1.2.0
127 silly install resolved [ { name: 'bindings',
127 silly install resolved     description: 'Helper module for loading your native module\'s .node file',
127 silly install resolved     keywords: [ 'native', 'addon', 'bindings', 'gyp', 'waf', 'c', 'c++' ],
127 silly install resolved     version: '1.2.1',
127 silly install resolved     author:
127 silly install resolved      { name: 'Nathan Rajlich',
127 silly install resolved        email: 'nathan@tootallnate.net',
127 silly install resolved        url: 'http://tootallnate.net' },
127 silly install resolved     repository:
127 silly install resolved      { type: 'git',
127 silly install resolved        url: 'git://github.com/TooTallNate/node-bindings.git' },
127 silly install resolved     main: './bindings.js',
127 silly install resolved     bugs: { url: 'https://github.com/TooTallNate/node-bindings/issues' },
127 silly install resolved     homepage: 'https://github.com/TooTallNate/node-bindings',
127 silly install resolved     license: 'MIT',
127 silly install resolved     gitHead: 'e404152ee27f8478ccbc7122ee051246e8e5ec02',
127 silly install resolved     _id: 'bindings@1.2.1',
127 silly install resolved     scripts: {},
127 silly install resolved     _shasum: '14ad6113812d2d37d72e67b4cacb4bb726505f11',
127 silly install resolved     _from: 'bindings@*',
127 silly install resolved     _npmVersion: '1.4.14',
127 silly install resolved     _npmUser: { name: 'tootallnate', email: 'nathan@tootallnate.net' },
127 silly install resolved     maintainers: [ [Object], [Object] ],
127 silly install resolved     dist:
127 silly install resolved      { shasum: '14ad6113812d2d37d72e67b4cacb4bb726505f11',
127 silly install resolved        tarball: 'http://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz' },
127 silly install resolved     directories: {},
127 silly install resolved     _resolved: 'https://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz',
127 silly install resolved     readme: 'ERROR: No README data found!' },
127 silly install resolved   { name: 'nan',
127 silly install resolved     version: '1.2.0',
127 silly install resolved     description: 'Native Abstractions for Node.js: C++ header for Node 0.8->0.12 compatibility',
127 silly install resolved     main: 'include_dirs.js',
127 silly install resolved     repository: { type: 'git', url: 'git://github.com/rvagg/nan.git' },
127 silly install resolved     contributors: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
127 silly install resolved     license: 'MIT',
127 silly install resolved     bugs: { url: 'https://github.com/rvagg/nan/issues' },
127 silly install resolved     homepage: 'https://github.com/rvagg/nan',
127 silly install resolved     _id: 'nan@1.2.0',
127 silly install resolved     dist:
127 silly install resolved      { shasum: '9c4d63ce9e4f8e95de2d574e18f7925554a8a8ef',
127 silly install resolved        tarball: 'http://registry.npmjs.org/nan/-/nan-1.2.0.tgz' },
127 silly install resolved     _from: 'nan@>=1.2.0 <1.3.0',
127 silly install resolved     _npmVersion: '1.4.3',
127 silly install resolved     _npmUser: { name: 'rvagg', email: 'rod@vagg.org' },
127 silly install resolved     maintainers: [ [Object] ],
127 silly install resolved     directories: {},
127 silly install resolved     _shasum: '9c4d63ce9e4f8e95de2d574e18f7925554a8a8ef',
127 silly install resolved     _resolved: 'https://registry.npmjs.org/nan/-/nan-1.2.0.tgz',
127 silly install resolved     readme: 'ERROR: No README data found!' } ]
128 info install bindings@1.2.1 into /home/ionicabizau/Documents/invoices/node_modules/weak
129 info install nan@1.2.0 into /home/ionicabizau/Documents/invoices/node_modules/weak
130 info installOne bindings@1.2.1
131 info installOne nan@1.2.0
132 verbose locking bindings with /home/ionicabizau/.npm/_locks/bindings-d36c0e3b2139334a.lock
133 verbose locking nan with /home/ionicabizau/.npm/_locks/nan-242c097250021dc1.lock
134 verbose unbuild node_modules/weak/node_modules/bindings
135 verbose unbuild node_modules/weak/node_modules/nan
136 verbose gentlyRm vacuuming /home/ionicabizau/Documents/invoices/node_modules/weak/node_modules/bindings
137 verbose gentlyRm vacuuming /home/ionicabizau/Documents/invoices/node_modules/weak/node_modules/nan
138 verbose tar unpack /home/ionicabizau/.npm/bindings/1.2.1/package.tgz
139 verbose tar unpacking to /home/ionicabizau/Documents/invoices/node_modules/weak/node_modules/bindings
140 verbose gentlyRm vacuuming /home/ionicabizau/Documents/invoices/node_modules/weak/node_modules/bindings
141 verbose tar unpack /home/ionicabizau/.npm/nan/1.2.0/package.tgz
142 verbose tar unpacking to /home/ionicabizau/Documents/invoices/node_modules/weak/node_modules/nan
143 verbose gentlyRm vacuuming /home/ionicabizau/Documents/invoices/node_modules/weak/node_modules/nan
144 silly gunzTarPerm modes [ '775', '664' ]
145 silly gunzTarPerm modes [ '775', '664' ]
146 silly gunzTarPerm extractEntry package.json
147 silly gunzTarPerm modified mode [ 'package.json', 420, 436 ]
148 silly gunzTarPerm extractEntry package.json
149 silly gunzTarPerm modified mode [ 'package.json', 420, 436 ]
150 silly gunzTarPerm extractEntry README.md
151 silly gunzTarPerm modified mode [ 'README.md', 420, 436 ]
152 silly gunzTarPerm extractEntry bindings.js
153 silly gunzTarPerm modified mode [ 'bindings.js', 420, 436 ]
154 silly gunzTarPerm extractEntry README.md
155 silly gunzTarPerm modified mode [ 'README.md', 420, 436 ]
156 silly gunzTarPerm extractEntry LICENSE
157 silly gunzTarPerm modified mode [ 'LICENSE', 420, 436 ]
158 silly gunzTarPerm extractEntry include_dirs.js
159 silly gunzTarPerm modified mode [ 'include_dirs.js', 420, 436 ]
160 silly gunzTarPerm extractEntry .dntrc
161 silly gunzTarPerm modified mode [ '.dntrc', 420, 436 ]
162 silly gunzTarPerm extractEntry build/config.gypi
163 silly gunzTarPerm modified mode [ 'build/config.gypi', 420, 436 ]
164 silly gunzTarPerm extractEntry nan.h
165 silly gunzTarPerm modified mode [ 'nan.h', 420, 436 ]
166 info preinstall bindings@1.2.1
167 silly install resolved []
168 verbose about to build /home/ionicabizau/Documents/invoices/node_modules/weak/node_modules/bindings
169 info build /home/ionicabizau/Documents/invoices/node_modules/weak/node_modules/bindings
170 verbose linkStuff [ false,
170 verbose linkStuff   false,
170 verbose linkStuff   false,
170 verbose linkStuff   '/home/ionicabizau/Documents/invoices/node_modules/weak/node_modules' ]
171 info linkStuff bindings@1.2.1
172 verbose linkBins bindings@1.2.1
173 verbose linkMans bindings@1.2.1
174 verbose rebuildBundles bindings@1.2.1
175 info install bindings@1.2.1
176 info postinstall bindings@1.2.1
177 verbose unlocking bindings from /home/ionicabizau/.npm/_locks/bindings-d36c0e3b2139334a.lock
178 info preinstall nan@1.2.0
179 silly install resolved []
180 verbose about to build /home/ionicabizau/Documents/invoices/node_modules/weak/node_modules/nan
181 info build /home/ionicabizau/Documents/invoices/node_modules/weak/node_modules/nan
182 verbose linkStuff [ false,
182 verbose linkStuff   false,
182 verbose linkStuff   false,
182 verbose linkStuff   '/home/ionicabizau/Documents/invoices/node_modules/weak/node_modules' ]
183 info linkStuff nan@1.2.0
184 verbose linkBins nan@1.2.0
185 verbose linkMans nan@1.2.0
186 verbose rebuildBundles nan@1.2.0
187 info install nan@1.2.0
188 info postinstall nan@1.2.0
189 verbose unlocking nan from /home/ionicabizau/.npm/_locks/nan-242c097250021dc1.lock
190 verbose about to build /home/ionicabizau/Documents/invoices/node_modules/weak
191 info build /home/ionicabizau/Documents/invoices/node_modules/weak
192 verbose linkStuff [ false,
192 verbose linkStuff   false,
192 verbose linkStuff   false,
192 verbose linkStuff   '/home/ionicabizau/Documents/invoices/node_modules' ]
193 info linkStuff weak@0.3.3
194 verbose linkBins weak@0.3.3
195 verbose linkMans weak@0.3.3
196 verbose rebuildBundles weak@0.3.3
197 verbose rebuildBundles [ 'bindings', 'nan' ]
198 info install weak@0.3.3
199 verbose unsafe-perm in lifecycle true
200 info weak@0.3.3 Failed to exec install script
201 verbose unlocking weak from /home/ionicabizau/.npm/_locks/weak-340264ce2fa49f33.lock
202 verbose stack Error: weak@0.3.3 install: `node-gyp rebuild`
202 verbose stack Exit status 1
202 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
202 verbose stack     at ChildProcess.emit (events.js:98:17)
202 verbose stack     at maybeClose (child_process.js:756:16)
202 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
203 verbose pkgid weak@0.3.3
204 verbose cwd /home/ionicabizau/Documents/invoices
205 error Linux 3.16.0-26-lowlatency
206 error argv "node" "/usr/local/bin/npm" "install" "weak"
207 error node v0.10.32
208 error npm  v2.1.2
209 error code ELIFECYCLE
210 error weak@0.3.3 install: `node-gyp rebuild`
210 error Exit status 1
211 error Failed at the weak@0.3.3 install script.
211 error This is most likely a problem with the weak package,
211 error not with npm itself.
211 error Tell the author that this fails on your system:
211 error     node-gyp rebuild
211 error You can get their info via:
211 error     npm owner ls weak
211 error There is likely additional logging output above.
212 verbose exit [ 1, true ]
213 verbose unbuild node_modules/weak
214 info preuninstall weak@0.3.3
215 info uninstall weak@0.3.3
216 verbose unbuild rmStuff weak@0.3.3 from /home/ionicabizau/Documents/invoices/node_modules
217 info postuninstall weak@0.3.3
218 verbose gentlyRm vacuuming /home/ionicabizau/Documents/invoices/node_modules/weak
219 silly gentlyRm purging /home/ionicabizau/Documents/invoices/node_modules/weak
220 silly gentlyRm removing /home/ionicabizau/Documents/invoices/node_modules
221 silly gentlyRm quitting because other entries in /home/ionicabizau/Documents/invoices
```

**Comment by IonicaBizau** [comment]
I guess this appeared because of some missing compilers.
