### ISSUE TITLE
Weak installation failed

### ISSUE THREAD

**Issue by idrakimuhamad** [TooTallNate/node-weak#55]
I'm installing Nightmare which installs weak, but I notice the installation failed. Tried to install it directly resulting the same error.

```
weak@1.0.0 install /Users/xxx/node_modules/weak
node-gyp rebuild

CXX(target) Release/obj.target/weakref/src/weakref.o
SOLINK_MODULE(target) Release/weakref.node

ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/weakref.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/idraki/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/Users/idraki/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xxx/node_modules/weak
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/xxx/.nvm/versions/node/v0.12.4/bin/node" "/Users/xxx/.nvm/versions/node/v0.12.4/bin/npm" "install" "weak"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! weak@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the weak@1.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the weak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls weak
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxx/npm-debug.log
```

I'm running OSX El-Capitan

**Comment by idrakimuhamad** [comment]
Turns out I need to use Xcode 7 command line tools. Now it let me pass. Thanks!
