### ISSUE TITLE
"compiler is out of heap space" error on install

### ISSUE THREAD

**Issue by fresheneesz** [TooTallNate/node-weak#74]
I can't install this module for node 5.1 on windows.

> >npm install weak
> 
> > weak@1.0.1 install D:\...\node_modules\weak
> > node-gyp rebuild
> 
> 
> D:\...\node_modules\weak>if not defined npm_config_node_gyp (node "C:\...\AppData\Roaming\nvm\v5.1.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>   weakref.cc
> D:\...\node_modules\nan\nan.h(70): fatal error C1060: compiler is out of heap space [D:\...\node_
> modules\weak\build\weakref.vcxproj]
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\...\AppData\Roaming\nvm\v5.1.0\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
> 
> gyp ERR! stack     at emitTwo (events.js:87:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Windows_NT 6.3.9600
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\...\\AppData\\Roaming\\nvm\\v5.1.0\\node_modules\\npm\\node_modules\\node-g
> yp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd D:\...\node_modules\weak
> gyp ERR! node -v v5.1.0
> gyp ERR! node-gyp -v v3.0.3
> gyp ERR! not ok
> npm WARN EPACKAGEJSON tests@0.0.0 No description
> npm WARN EPACKAGEJSON tests@0.0.0 No repository field.
> npm WARN EPACKAGEJSON tests@0.0.0 No license field.
> npm ERR! Windows_NT 6.3.9600
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "weak"
> npm ERR! node v5.1.0
> npm ERR! npm  v3.3.12
> npm ERR! code ELIFECYCLE
> 
> npm ERR! weak@1.0.1 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the weak@1.0.1 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the weak package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls weak
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     D:\...\node-weak\npm-debug.log

**Comment by KatherineZhu** [comment]
me too, I use command `npm install --python=python.exe --msvs_version=2012 weak` and nodejs 5.6.0, npm version 3.6.0.

**Comment by jeanru** [comment]
+1
C:\Users\leon\AppData\Roaming\npm\node_modules\xml2json\node_modules\nan\nan.h(74): fatal error C1060: compiler is out of heap space (..\node-expat.cc) [C:\Users\leon\AppData\Roaming\npm\node_modules\xml2json\node_modules\node-expat\bui
ld\node_expat.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\leon\AppData\Roaming\npm\node_modules\xml2json\node_modules\node-expat
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
